INSERT INTO CATEGORIA(nome) VALUES ('Informática');
INSERT INTO CATEGORIA(nome) VALUES ('Escritório');

INSERT INTO PRODUTO(nome, preco) VALUES ('Computador', 2000.00);
INSERT INTO PRODUTO(nome, preco) VALUES ('Computador', 2000.00);
INSERT INTO PRODUTO(nome, preco) VALUES ('Impressora', 800.00);
INSERT INTO PRODUTO(nome, preco) VALUES ('Mouse', 80.00);

INSERT INTO PRODUTO_CATEGORIA VALUES (1, 1);
INSERT INTO PRODUTO_CATEGORIA VALUES (2, 1);
INSERT INTO PRODUTO_CATEGORIA VALUES (2, 2);
INSERT INTO PRODUTO_CATEGORIA VALUES (3, 1);